version: '2'
services:
  mongo-cluster:
    image: mongo:3.2
    environment:
      CATTLE_SCRIPT_DEBUG: ''
      MONGO_SERVICE_NAME: mongo-cluster
    entrypoint:
    - /opt/rancher/bin/entrypoint.sh
    volumes:
    - /data/db:/data/db
    volumes_from:
    - mongo-base
    command:
    - --replSet
    - rs0
    labels:
      io.rancher.scheduler.affinity:host_label: ''
      io.rancher.sidekicks: mongo-base
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'
  mongo-base:
    image: rancher/mongodb-conf:v0.1.1
    stdin_open: true
    entrypoint:
    - /bin/true
    network_mode: none
    labels:
      io.rancher.scheduler.affinity:host_label: ''
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
