version: '2'
services:
  mongo-cluster:
    metadata:
      mongo: null
    retain_ip: true
    start_on_create: true
  mongo-base:
    metadata:
      mongo: null
    retain_ip: true
    scale: 1
    start_on_create: true
